# Generated by Django 3.2.3 on 2021-06-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='description',
            field=models.DateField(max_length=300),
        ),
    ]
